export const POST_TEAM_MAX_LENGTH = 10000;
export const POST_TEAM_COMMENT_MAX_LENGTH = 10000;
export const POST_QUESTION_MAX_LENGTH = 30000;
export const POST_QUESTION_COMMENT_MAX_LENGTH = 30000;
export const POST_SHARING_MAX_LENGTH = 30000;
export const POST_SHARING_COMMENT_MAX_LENGTH = 10000;

export const TITLE_MAX_LENGTH = 255;

export const TOPIC_MAX_LENGTH = 50;
export const MAX_NUMBER_OF_TOPICS = 20;

export const MIN_TEAM_SIZE = 1;
export const MAX_TEAM_SIZE = 100;
