export const POST_TEAM_MAX_LENGTH = 10000;
export const POST_TEAM_COMMENT_MAX_LENGTH = 10000;
export const POST_QUESTION_MAX_LENGTH = 30000;
export const POST_QUESTION_COMMENT_MAX_LENGTH = 30000;
export const POST_SHARING_MAX_LENGTH = 30000;
export const POST_SHARING_COMMENT_MAX_LENGTH = 10000;

export const MAX_TOPIC_NUMBER = 20;
